repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict
      - id: sort-simple-yaml

  - repo: https://github.com/psf/black
    rev: 'refs/tags/25.1.0:refs/tags/25.1.0'
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML", "types-requests", "types-python-slugify", "pydantic~=2.0"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
